user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /



reservation:
    resource: "@reservationBundle/Resources/config/routing.yml"
    prefix:   /

techevent:
    resource: "@techeventBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"